version: "3"

services:
  rust_app_instance_1:
    image: app:latest
    environment:
      - INSTANCE_NAME=Server1
    ports:
      - "3000"

  rust_app_instance_2:
    image: app:latest
    environment:
      - INSTANCE_NAME=Server2
    ports:
      - "3000"
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - rust_app_instance_1
      - rust_app_instance_2